// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package injector

import (
	"api/internal/cron"
	handlers2 "api/internal/features/general/handlers"
	injector2 "api/internal/features/general/injector"
	"api/internal/features/general/repositories"
	services2 "api/internal/features/general/services"
	"api/internal/features/gold/handlers"
	"api/internal/features/gold/injector"
	repositories2 "api/internal/features/gold/repositories"
	"api/internal/features/gold/services"
	handlers3 "api/internal/features/user/handlers"
	injector3 "api/internal/features/user/injector"
	repositories3 "api/internal/features/user/repositories"
	services3 "api/internal/features/user/services"
	"api/pkg/database"
	"api/pkg/market"
)

// Injectors from cron.go:

func InitGoldCron() *cron.Gold {
	marketMarket := market.New()
	db := database.New()
	asset := repositories.NewAsset(db)
	gold := cron.NewGold(marketMarket, asset)
	return gold
}

func InitDollarCron() *cron.Dollar {
	marketMarket := market.New()
	db := database.New()
	currency := repositories.NewCurrency(db)
	dollar := cron.NewDollar(marketMarket, currency)
	return dollar
}

// Injectors from handlers.go:

func InitGoldHandlers() *injector.GoldHandlers {
	db := database.New()
	gold := repositories2.NewGold(db)
	asset := repositories.NewAsset(db)
	currency := repositories.NewCurrency(db)
	servicesGold := services.NewGold(gold, asset, currency)
	handlersGold := handlers.NewGold(servicesGold)
	goldHandlers := injector.NewGoldHandlers(handlersGold)
	return goldHandlers
}

func InitGeneralHandlers() *injector2.GeneralHandlers {
	db := database.New()
	asset := repositories.NewAsset(db)
	currency := repositories.NewCurrency(db)
	gold := repositories2.NewGold(db)
	general := services2.NewGeneral(asset, currency, gold)
	handlersGeneral := handlers2.NewGeneral(general)
	generalHandlers := injector2.NewGeneralHandlers(handlersGeneral)
	return generalHandlers
}

func InitUserHandlers() *injector3.UserHandlers {
	db := database.New()
	user := repositories3.NewUser(db)
	session := repositories3.NewSession(db)
	auth := services3.NewAuth(user, session, db)
	handlersAuth := handlers3.NewAuth(auth)
	userHandlers := injector3.NewUserHandlers(handlersAuth)
	return userHandlers
}
